baseurl = "https://blog.leins275.xyz/"
theme = "hugo-coder"
enableInlineShortcodes = true
pygmentsstyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = 'leins275-xyz-1'
enableEmoji = true

languageCode = "ru"
defaultContentLanguage = "ru"

title = "leins275"
copyright = "leins275 All rights reserved"

[pagination]
  pagerSize = 20

[[menu.main]]
  name = "–ë–ª–æ–≥"
  weight = 3
  url  = "posts/"

[author]
  name = "leins275"
  email = "leins275@gmail.com"

[params]
  author      = "Nikita Lanskov"
  info        = "Full Stack DevOps and Magician"
  description = "leins275 personal website"
  keywords    = "blog,developer,personal"
  gravatar    = "leins275@gmail.com"
  dateFormat  = "02.01.2006"

  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"

  footercontent = "The meaning of life is to grow in power."
  hideFooter    = false
  hideCredits   = false
  hideCopyright = false
  since         = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  katex = true

[taxonomies]
  series   = "series"
  category = "categories"
  tag = "tags"

# Social links
[[params.social]]
  name   = "Github"
  icon   = "fa fa-github fa-2x"
  weight = 1
  url    = "https://github.com/leins275/"
[[params.social]]
  name   = "Telegram"
  icon   = "fa fa-telegram fa-2x"
  weight = 2
  url    = "https://t.me/nlanskov"
[[params.social]]
  name   = "Vk"
  icon   = "fa fa-vk fa-2x"
  weight = 3
  url    = "https://vk.com/leins275"
[[params.social]]
  name   = "LinkedIn"
  icon   = "fa fa-linkedin fa-2x"
  weight = 4
  url    = "https://www.linkedin.com/in/leins275/"
[[params.social]]
  name   = "Instagram"
  icon   = "fa fa-instagram fa-2x"
  weight = 5
  url    = "https://www.instagram.com/leins275/"
[[params.social]]
  name   = "Youtube"
  icon   = "fa fa-youtube fa-2x"
  weight = 9
  url    = "https://www.youtube.com/@leins275"
[[params.social]]
  name   = "RSS"
  icon   = "fa fa-rss fa-2x"
  weight = 10
  url    = "https://leins275.xyz/index.xml"
  rel    = "alternate"
  type   = "application/rss+xml"

[params.yandexMetrika]
  id = "97527726"
[params.googleTagManager]
  id = "G-XQT1SSWG4Z"

# Menu links

# Sitemap settings
[sitemap]
  changefreq = 'monthly'
  filename   = 'sitemap.xml'
  priority   = 0.5

# Languages

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[languages.ru]
languageName = "üá∑üá∫"
title = "–ù–∏–∫–∏—Ç–∞ –õ–∞–Ω—Å–∫–æ–≤"

[languages.ru.params]
author = "–ù–∏–∫–∏—Ç–∞ –õ–∞–Ω—Å–∫–æ–≤"
info = "Fullstack DevOps and Magician"
description = "–õ–∏—á–Ω—ã–π –±–ª–æ–≥"
keywords = "–±–ª–æ–≥"

[[languages.ru.menu.main]]
name = "–ë–ª–æ–≥"
weight = 2
url = "posts/"